# Generated by Django 4.0.5 on 2022-09-18 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogi6', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_like',
            fields=[
                ('like_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150, unique=True)),
                ('exhibition_id', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='User_review',
            fields=[
                ('review_id', models.AutoField(primary_key=True, serialize=False)),
                ('username', models.CharField(max_length=150)),
                ('exhibition_id', models.IntegerField()),
                ('title', models.CharField(max_length=150)),
                ('detail', models.TextField()),
                ('star', models.FloatField()),
                ('date_joined', models.DateTimeField()),
            ],
        ),
        migrations.AlterModelOptions(
            name='user',
            options={'managed': False},
        ),
    ]
