# Generated by Django 3.2.15 on 2022-09-23 23:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yogi6', '0003_auto_20220922_2126'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='user_like',
            table='yogi6_user_like',
        ),
        migrations.AlterModelTable(
            name='user_review',
            table='yogi6_user_review',
        ),
    ]
