# Generated by Django 3.2.15 on 2022-09-28 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yogi6', '0004_auto_20220923_2333'),
    ]

    operations = [
        migrations.CreateModel(
            name='Summary',
            fields=[
                ('summary_id', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=500)),
                ('rating', models.IntegerField()),
                ('summary', models.TextField(blank=True, null=True)),
                ('star', models.FloatField()),
                ('review_num', models.IntegerField()),
            ],
            options={
                'db_table': 'summary',
                'managed': False,
            },
        ),
    ]
